### ISSUE TITLE
Budjettilaskurin taustakuva toistaa itseään rumasti kun selainikkunan koko >1920x1080 px

### ISSUE THREAD

**Issue by ojaha065** [ojela028xamk/react-projects#16]
Kts. ruudunkaappaus

![probleemi_JL](https://user-images.githubusercontent.com/37581768/140636717-a3cdb948-d19e-4061-849a-91c01caeb9a3.png)

**Comment by ojela028xamk** [comment]
Kiitos huomautuksesta, mahtaakohan siellä pelien toivelistasivustolla myös toistua se gradientti?

**Comment by ojaha065** [comment]
En toki tiedä, että miltä sen kuuluisi näyttää, mutta pikaisella silmäyksellä gradientti näyttäisi toimivan oikein.

**Comment by ojela028xamk** [comment]
Juu se toimii. Mä vaihdan ton budjettisivun taustan.
